openapi: 3.0.0
info:
  title: Invoice Management API
  version: 1.0.0
paths:
  /api/invoices:
    get:
      summary: Display List of Invoices
      responses:
        '200':
          description: A list of invoices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    invoice_id:
                      type: integer
                      example: 1
                    user_id:
                      type: integer
                      example: 1
                    invoice_date:
                      type: string
                      format: date
                      example: "2023-01-01"
                    total_amount:
                      type: number
                      format: float
                      example: 150.00
                    status:
                      type: string
                      example: "Paid"
                    created_at:
                      type: string
                      format: date-time
                      example: "2023-01-01T10:00:00Z"
  /api/invoices/{invoice_id}:
    get:
      summary: View Invoice Details
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: integer
          description: The ID of the invoice to retrieve
      responses:
        '200':
          description: Invoice details
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_id:
                    type: integer
                    example: 1
                  user_id:
                    type: integer
                    example: 1
                  invoice_date:
                    type: string
                    format: date
                    example: "2023-01-01"
                  total_amount:
                    type: number
                    format: float
                    example: 150.00
                  status:
                    type: string
                    example: "Paid"
                  created_at:
                    type: string
                    format: date-time
                    example: "2023-01-01T10:00:00Z"
                  line_items:
                    type: array
                    items:
                      type: object
                      properties:
                        line_item_id:
                          type: integer
                          example: 1
                        description:
                          type: string
                          example: "Monthly Subscription"
                        quantity:
                          type: integer
                          example: 1
                        unit_price:
                          type: number
                          format: float
                          example: 100.00
                        total_price:
                          type: number
                          format: float
                          example: 100.00
                        created_at:
                          type: string
                          format: date-time
                          example: "2023-01-01T10:00:00Z"
  /api/invoices/{invoice_id}/line_items/{line_item_id}:
    get:
      summary: Select Line Item for Change
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: integer
          description: The ID of the invoice
        - in: path
          name: line_item_id
          required: true
          schema:
            type: integer
          description: The ID of the line item to retrieve
      responses:
        '200':
          description: Line item details
          content:
            application/json:
              schema:
                type: object
                properties:
                  line_item_id:
                    type: integer
                    example: 1
                  invoice_id:
                    type: integer
                    example: 1
                  description:
                    type: string
                    example: "Monthly Subscription"
                  quantity:
                    type: integer
                    example: 1
                  unit_price:
                    type: number
                    format: float
                    example: 100.00
                  total_price:
                    type: number
                    format: float
                    example: 100.00
                  created_at:
                    type: string
                    format: date-time
                    example: "2023-01-01T10:00:00Z"
  /api/change_requests:
    post:
      summary: Submit Change Request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                line_item_id:
                  type: integer
                  example: 1
                user_id:
                  type: integer
                  example: 1
                request_description:
                  type: string
                  example: "Change the description to 'Monthly Plan Subscription'"
                status:
                  type: string
                  example: "Pending"
      responses:
        '201':
          description: Change request submitted
          content:
            application/json:
              schema:
                type: object
                properties:
                  change_request_id:
                    type: integer
                    example: 1
                  line_item_id:
                    type: integer
                    example: 1
                  user_id:
                    type: integer
                    example: 1
                  request_description:
                    type: string
                    example: "Change the description to 'Monthly Plan Subscription'"
                  status:
                    type: string
                    example: "Pending"
                  created_at:
                    type: string
                    format: date-time
                    example: "2023-03-01T10:00:00Z"
  /api/refund_requests:
    post:
      summary: Request Refund for Invoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice_id:
                  type: integer
                  example: 1
                user_id:
                  type: integer
                  example: 1
                request_description:
                  type: string
                  example: "Requesting a full refund for incorrect charges"
                status:
                  type: string
                  example: "Pending"
      responses:
        '201':
          description: Refund request submitted
          content:
            application/json:
              schema:
                type: object
                properties:
                  refund_request_id:
                    type: integer
                    example: 1
                  invoice_id:
                    type: integer
                    example: 1
                  user_id:
                    type: integer
                    example: 1
                  request_description:
                    type: string
                    example: "Requesting a full refund for incorrect charges"
                  status:
                    type: string
                    example: "Pending"
                  created_at:
                    type: string
                    format: date-time
                    example: "2023-03-01T10:00:00Z"